name: flutter_stater
description: "A lightweight and well-structured Flutter starter template with Clean Architecture, localization support, and essential configurations to kickstart new Flutter projects efficiently."
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


